import fs from "node:fs";
import path from "node:path";

import PDFDocument from "pdfkit";

import { env } from "../config/env.js";

interface CvProfile {
  name: string;
  nameJp?: string | null;
  email: string;
  phone?: string | null;
  originCity?: string | null;
  jlptLevel?: string | null;
  specialization?: string[] | string | null;
  education?: Array<{
    year?: string | number;
    degree?: string;
    institution?: string;
  }>;
  experience?: Array<{
    start?: string;
    end?: string;
    title?: string;
    company?: string;
  }>;
  bioId?: string | null;
  bioJp?: string | null;
}

const FONT_CANDIDATES = ["NotoSansCJKjp-Regular.otf"];

function getFontPath(): string | null {
  for (const name of FONT_CANDIDATES) {
    const p = path.join(process.cwd(), "fonts", name);
    if (fs.existsSync(p)) return p;
  }
  return null;
}

export function streamCvPdf(
  profile: CvProfile,
  res: import("http").ServerResponse,
): void {
  const doc = new PDFDocument({
    size: "A4",
    margin: 50,
    info: { Title: `Rirekisho - ${profile.name}` },
  });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="rirekisho-${profile.name.replace(/\s+/g, "_")}.pdf"`,
  );
  doc.pipe(res);

  const font = getFontPath();
  if (font) {
    doc.registerFont("jp", font);
    doc.font("jp");
  }

  doc.fontSize(20).text("履歴書 (Rirekisho)", { align: "center" });
  doc.moveDown(0.5);
  doc.fontSize(16).text(profile.nameJp || profile.name, { align: "center" });
  if (profile.nameJp) doc.fontSize(12).text(profile.name, { align: "center" });
  doc.moveDown();

  doc.fontSize(11);
  const row = (label: string, value: string | null | undefined): void => {
    if (!value) return;
    doc.text(`${label}: ${value}`);
  };
  row("Email", profile.email);
  row("Telepon / 電話", profile.phone);
  row("Asal / 出身", profile.originCity);
  row("JLPT", profile.jlptLevel);
  row(
    "Spesialisasi / 専門",
    Array.isArray(profile.specialization)
      ? profile.specialization.join(", ")
      : profile.specialization,
  );
  doc.moveDown();

  if (profile.education && profile.education.length) {
    doc.fontSize(13).text("学歴 / Pendidikan");
    doc.moveDown(0.3);
    doc.fontSize(10);
    profile.education.forEach((e) =>
      doc.text(
        `• ${e.year ?? ""} — ${e.degree ?? ""} — ${e.institution ?? ""}`,
      ),
    );
    doc.moveDown();
  }

  if (profile.experience && profile.experience.length) {
    doc.fontSize(13).text("職歴 / Pengalaman Kerja");
    doc.moveDown(0.3);
    doc.fontSize(10);
    profile.experience.forEach((x) =>
      doc.text(
        `• ${x.start ?? ""} – ${x.end ?? "sekarang"} — ${x.title ?? ""} @ ${x.company ?? ""}`,
      ),
    );
    doc.moveDown();
  }

  if (profile.bioJp || profile.bioId) {
    doc.fontSize(13).text("自己紹介 / Bio");
    doc.moveDown(0.3);
    doc.fontSize(10);
    if (profile.bioJp) doc.text(`JP: ${profile.bioJp}`);
    if (profile.bioId) doc.text(`ID: ${profile.bioId}`);
    doc.moveDown();
  }

  doc
    .fontSize(8)
    .fillColor("#888")
    .text(`Generated by JIJP pada ${new Date().toLocaleString("id-ID")}`, {
      align: "right",
    });
  doc.end();
}

void env;
